### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by jhoelzl** [schmengler/TranslationHints#2]
Hello,

i get an error on magento frontend when enabling the module:

Parse error: syntax error, unexpected '[', expecting ')' in app/code/community/SSE/TranslationHints/Model/Data.php on line 43

When i change this

```
 return serialize([$this->_data, $this->_metaData]);
```

to

```
 return serialize($this->_data, $this->_metaData);
```

it works. I have PHP 5.3.3

**Comment by jhoelzl** [comment]
Ah, sorry i forgot to see the requirements: PHP 5.4 or higher

**Comment by schmengler** [comment]
If you really need to, you could patch it to work with PHP 5.3, but then it should be 

```
return serialize(array($this->_data, $this->_metaData));
```

But I strongly recommend updating to PHP 5.4
