### ISSUE TITLE
With manual installation module configuration is not showing in System > Configuration > Advanced > Developer > Debug (CE v.1.9.2.4)

### ISSUE THREAD

**Issue by kanenas** [schmengler/TranslationHints#3]
**Magento Core**: CE v.1.9.2.4

When using **manual installation** of the module, module configuration is not showing up in `System > Configuration > Advanced > Developer > Debug` see the attachment **system-configuration-advanced-developer-debug.jpg**, 
![system-configuration-advanced-developer-debug](https://cloud.githubusercontent.com/assets/327786/15743126/e6caadec-28cb-11e6-940e-82c77261819c.jpg)
although it is enabled in `System > Configuration > Advanced > Advanced` see the attachment **system-configuration-advanced-advanced.jpg**. 
![system-configuration-advanced-advanced](https://cloud.githubusercontent.com/assets/327786/15743210/7c060e9c-28cc-11e6-861c-3ed59a985529.jpg)

**Comment by schmengler** [comment]
It's only available in store scope, in the same way as the template hints

**Comment by kanenas** [comment]
Oops... Mea culpa!
